site_name: ngsJulia
site_url: https://ngsjulia.readthedocs.io/

nav:
  - Home: 'index.md'
  - 'Install': 'install.md'
  - 'API':
    - 'List': 'api.md'
    - 'Custom': 'custom.md'
    - 'Auxiliary': 'aux.md'
  - 'CLI':
    - 'ngsPloidy': 'ngsPloidy.md'
    - 'ngsPool': 'ngsPool.md'

theme:
    name: readthedocs


