site_name: ngsJulia
site_url: https://ngsjulia.readthedocs.io/

nav:
  - Home: 'index.md'
  - 'Install': 'install.md'
  - 'API':
    - 'List of functions': 'api.md'
    - 'Custom analysis': 'custom.md'
    - 'Auxiliary R scripts': 'aux.md'
  - 'CLI':
    - 'ngsPloidy': 'ngsPloidy.md'
    - 'ngsPool': 'ngsPool.md'

theme:
    name: readthedocs


