site_name: ngsJulia-doc
  # site_url: 

nav:
  - Home: 'index.md'
  - 'Install': 'install.md'
  - 'API':
    - 'List': 'api.md'
    - 'Custom': 'custom.md'
  - 'CLI':
    - 'ngsPloidy': 'ngsPloidy.md'
    - 'ngsPool': 'ngsPool.md'

theme:
    name: readthedocs



